### ISSUE TITLE
Pád na Android 4.4.4 při kliknutí na funkci vlaku

### ISSUE THREAD

**Issue by kudlav** [kmzbrnoI/hJOPandroidDriver#26]
Chyba verzi 1.8 i 1.7

Zařízení: samsung GT-I9195I

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cz.mendelu.xmarik.train_manager, PID: 24803
    java.lang.ClassCastException: android.support.v7.widget.TintContextWrapper cannot be cast to cz.mendelu.xmarik.train_manager.activities.TrainHandler
        at cz.mendelu.xmarik.train_manager.adapters.FunctionCheckBoxAdapter.chb_onClick(FunctionCheckBoxAdapter.java:84)
        at cz.mendelu.xmarik.train_manager.adapters.FunctionCheckBoxAdapter$2.onClick(FunctionCheckBoxAdapter.java:61)
        at android.view.View.performClick(View.java:4888)
        at android.view.View$PerformClick.run(View.java:19743)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5756)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kudlav** [comment]
Opraveno v https://github.com/kmzbrnoI/hJOPandroidDriver/commit/bacc38d5da623be83a99037f68022885e37bd365
