### ISSUE TITLE
Pád při obnovení aplikace z pozadí

### ISSUE THREAD

**Issue by kudlav** [kmzbrnoI/hJOPandroidDriver#30]
Frekvence výskytu nízká. Nutno zjistit, jak lze reprodukovat.
```
2020-09-17 22:21:55.325 19227-19227/cz.mendelu.xmarik.train_manager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cz.mendelu.xmarik.train_manager, PID: 19227
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.mendelu.xmarik.train_manager/cz.mendelu.xmarik.train_manager.activities.TrainHandler}: java.lang.NullPointerException: Attempt to read from field 'java.util.Map cz.mendelu.xmarik.train_manager.storage.TrainDb.trains' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.Map cz.mendelu.xmarik.train_manager.storage.TrainDb.trains' on a null object reference
        at cz.mendelu.xmarik.train_manager.activities.TrainHandler.fillHVs(TrainHandler.java:208)
        at cz.mendelu.xmarik.train_manager.activities.TrainHandler.onCreate(TrainHandler.java:136)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3531)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7948) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075) 
```

**Comment by kudlav** [comment]
this shloud be fixed by 450158cae8ad76d674fd7e8305b5bdeaf14bc0bf
